group.all_automations:
  friendly_name: 'All Automations'
  hidden: True

group.all_covers:
  friendly_name: 'All Covers'
  hidden: True

group.all_devices:
  friendly_name: 'All Devices'
  hidden: True

group.all_lights:
  friendly_name: 'All Lights'
  hidden: True

group.all_scripts:
  friendly_name: 'All Scripts'
  hidden: True

group.all_switches:
  friendly_name: 'All Switches'
  hidden: True
