homeassistant:
  name: Hillside
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Australia/Brisbane
  
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "automation.*watchdog*":
      icon: mdi:timer
    "sensor.dark_sky_*":
      homebridge_hidden: true

  packages: !include_dir_named packages

frontend:
  javascript_version: latest

config:

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  trusted_networks:
    - 192.168.100.0/24

updater:
  include_used_components: true

discovery:

history:

logbook:
  exclude:
    entities:
      - automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
      - automation.cuckoo_clock
      - binary_sensor.office_motion
      - group.garage_doors
      - media_player.LivingRoomCC
      - py.warnings
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.small_garage_status
      - sensor.large_garage_status
      - sensor.small_garage_time_in_state
      - sensor.large_garage_time_in_state
      - sensor.large_garage_wifi_signal_strength
      - sensor.small_garage_wifi_signal_strength
      - sensor.small_garage_reflection_rate
      - sensor.large_garage_reflection_rate
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.time
      - sensor.date
      - sensor.floorplan_date
      - sensor.floorplan_time
      - sensor.ha_uptime

map:

sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret tts_aws_access_key 
    aws_secret_access_key: !secret tts_asw_secret
    voice: Emma
    text_type: ssml
    cache: True

cloud:

device_tracker:
  - platform: unifi
    host: unifi.foxthree.net
    username: hass
    password: !secret dt_unifi
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

logger: !include logger.yaml
recorder: !include recorder.yaml

group: !include_dir_merge_named group
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
