- platform: bayesian
  prior: 0.5
  name: 'Beau Presence'
  probability_threshold: 0.8
  observations:
    - entity_id: 'device_tracker.beau'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.beau_iphone'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'